// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKyJy6DCQRrT3oYGwJ_Okgbi4MjIDTy8A',
    appId: '1:656987239974:web:cb161d5849480fb66058e7',
    messagingSenderId: '656987239974',
    projectId: 'lumio-2512c',
    authDomain: 'lumio-2512c.firebaseapp.com',
    storageBucket: 'lumio-2512c.firebasestorage.app',
    measurementId: 'G-ZS1F647SVF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrSbUT4E2XIwLYfg3RbbSsBWBId0U1_N8',
    appId: '1:656987239974:android:7a7f431ffd8d4e7d6058e7',
    messagingSenderId: '656987239974',
    projectId: 'lumio-2512c',
    storageBucket: 'lumio-2512c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVQ5PlDcsh18iK8H_70Lr_hsKJrgFm6Ms',
    appId: '1:656987239974:ios:ee66512ebbd5400f6058e7',
    messagingSenderId: '656987239974',
    projectId: 'lumio-2512c',
    storageBucket: 'lumio-2512c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVQ5PlDcsh18iK8H_70Lr_hsKJrgFm6Ms',
    appId: '1:656987239974:ios:ee66512ebbd5400f6058e7',
    messagingSenderId: '656987239974',
    projectId: 'lumio-2512c',
    storageBucket: 'lumio-2512c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKyJy6DCQRrT3oYGwJ_Okgbi4MjIDTy8A',
    appId: '1:656987239974:web:9fabd339b7fe22e36058e7',
    messagingSenderId: '656987239974',
    projectId: 'lumio-2512c',
    authDomain: 'lumio-2512c.firebaseapp.com',
    storageBucket: 'lumio-2512c.firebasestorage.app',
    measurementId: 'G-DK0NCJVDCK',
  );
}
